### PR TITLE
Fix #540 Detect unused variable declared multiple times

### LINKED ISSUE #540: UnusedLocalVariable doesn't detect unused var when defined twice
```PHP
function testUnused()
{
    $worthlessVar = false;
    $worthlessVar = true;
}
```

phpmd fails to raise any UnusedLocalVariable notice re `$worthlessVar`

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #540
Breaking change: no

### CODE REVIEW

File: src/main/php/PHPMD/Rule/UnusedLocalVariable.php [hunk 1]
```diff
@@ -50,12 +50,33 @@ public function apply(AbstractNode $node)
...
 
         foreach ($this->images as $nodes) {
-            if (count($nodes) === 1) {
+            if (!$this->containsUsages($nodes)) {
                 $this->doCheckNodeImage($nodes[0]);
             }
         }
     }
 
+    private function containsUsages(array $nodes)
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/UnusedLocalVariable.php:59]: Missing doc block

File: src/main/php/PHPMD/Rule/UnusedLocalVariable.php [hunk 2]
```diff
@@ -251,12 +276,6 @@ private function isChildOf(AbstractNode $node, $type)
...
     private function getExceptionsList()
     {
-        try {
-            $exceptions = $this->getStringProperty('exceptions');
-        } catch (\OutOfBoundsException $e) {
-            $exceptions = '';
-        }
-
-        return explode(',', $exceptions);
+        return explode(',', $this->getStringProperty('exceptions', ''));
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/UnusedLocalVariable.php:279]: Good riddance!
