### PR TITLE
Fix PHP 8 deprecation notices on the fly for phar build

### LINKED ISSUE #881: Phar throwing errors in PHP 8.0.
- PHPMD version: 2.10.0
- PHP Version: 8.0.3
- Installation type: phar
- Operating System / Distribution & Version: macOS

### Current Behavior
I'm seeing multiple errors during a single lint execution.
```
./Bin/phpmd Test.php json cleancode,codesize,controversial,design,naming,unusedcode 
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 54

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 54
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 68

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 68
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 517

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 517
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 519

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 519
{
    "version": "2.10.0snapshot202104261849",
    "package": "phpmd",
    "timestamp": "2021-04-27T02:27:17+00:00",
    "files": [
        {
            "file": "\/Users\/mike\/Developer\/phpmd.novaextension\/Test.php",
            "violations": [
                {
                    "beginLine": 3,
                    "endLine": 6,
                    "package": "+global",
                    "function": null,
                    "class": "Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf",
                    "method": null,
                    "description": "Avoid excessively long class names like Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf. Keep class name length under 40.",
                    "rule": "LongClassName",
                    "ruleSet": "Naming Rules",
                    "externalInfoUrl": "https:\/\/phpmd.org\/rules\/naming.html#longclassname",
                    "priority": 3
                }
            ]
        }
    ]
}
```

### Expected Behavior
- The errors make it difficult to parse the results programatically.
- I would expect `libxml_disable_entity_loader()` not to be referenced when running in PHP 8.

### Steps To Reproduce:
Run the above command on the following file:
```php
<?php

class Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf
{
    //
}
```

## Checks before submitting
* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: feature
Issue: Resolves #881
Breaking change: no

While checking PHAR generation, the hook ensuring our own code pass some rules, it failed on `UndefinedVariable` which has complexity > 50. So in order to keep the complexity below and have the PHAR generation still working without increasing the threshold, I also took the opportunity to dedupe some code in `UndefinedVariable` class.

### CODE REVIEW

File: src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php [hunk 1]
```diff
@@ -172,17 +160,13 @@ protected function collectListExpressions(AbstractCallableNode $node)
...
-                    $this->addVariableDefinition($children);
-                } elseif ($children instanceof ASTUnaryExpression) {
-                    foreach ($children->getChildren() as $refChildren) {
-                        if ($refChildren instanceof ASTVariable) {
-                            $this->addVariableDefinition($refChildren);
-                        }
+        foreach ($node->findChildrenWithParentType('ForeachStatement') as $child) {
+            if ($child instanceof ASTVariable) {
+                $this->addVariableDefinition($child);
+            } elseif ($child instanceof ASTUnaryExpression) {
```
Comment (tvbeek) [inline src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php:166]: Maybe you can lower the indentation by using continue to skip a part of the foreach block.
```suggestion
                continue;
            }
            if (!($child instanceof ASTUnaryExpression)) {
                continue;
            }
```

**Review by tvbeek — COMMENTED** [review]
Nice improvement, I have one little comment. The other parts looks good.

**Review by tvbeek — APPROVED** [review]
