### PR TITLE
Fix #672 Try global function if namespaced one is not found

### LINKED ISSUE #672: CleanCode\UndefinedVariable thrown unnecessarily with preg_match_all()
- PHPMD version: dev-master (SHA b9eaa0fe7f38c1f017a5ed8564f1cd63d136ed2c)
- PHP Version: 7.1.31
- Installation type: composer
- Operating System / Distribution & Version: MacOS X

### Current Behavior
UndefinedVariable error thrown unnecessarily when variable is guaranteed to be defined by `preg_match_all()`

### Expected Behavior
UndefinedVariable error not thrown for third argument to `preg_match_all()` when used.

### Steps To Reproduce:
The following code triggers the following warnings:
```
test.php:5	Avoid using undefined variables such as '$matches' which will lead to PHP notices.
test.php:6	Avoid using undefined variables such as '$matches' which will lead to PHP notices.
```
However, PHP won't throw warnings in this case, so the error is spurious. 

```php
<?php

function test()
{
    preg_match_all('/./', 'Text', $matches);
    foreach ($matches[0] as $match) {
        echo $match . PHP_EOL;
    }
}
```

There's also an inconsistency as the same code when not wrapped in a function does not throw the warnings (as I'd expect), e.g. the following code (correctly IMHO) does not generate an UndefinedVariable warning from PHPMD:

```php
<?php

preg_match_all('/./', 'Text', $matches);
foreach ($matches[0] as $match) {
    echo $match . PHP_EOL;
}
```

```
## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Resolves #672 #840
Breaking change: no

When using `preg_match_all` in a file having a namespace (with PHP >= 7.1), PHP actually try to load `X\preg_match_all` then `preg_match_all`, PDepend actually resolves it as `X\preg_match_all` so when looking into a function name, PHPMD must try both (in the same order as PHP).

A first case is in the fix of #672 for arguments passed by reference.

### CODE REVIEW

File: src/main/php/PHPMD/Node/Annotation.php [hunk 1]
```diff
@@ -18,6 +18,7 @@
 namespace PHPMD\Node;
 
 use PHPMD\Rule;
+use PHPMD\Rule\Design\LongClass;
```
Comment (ravage84) [inline src/main/php/PHPMD/Node/Annotation.php:21]: Why was this added?

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 2]
```diff
@@ -264,6 +264,33 @@ protected function getNode($node)
         return $node;
     }
 
+    /**
+     * Reflect function trying as namespaced function first, then global function.
+     *
+     * @param string $functionName
+     *
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:271]: Superfluous line

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 3]
```diff
@@ -275,20 +302,15 @@ protected function isPassedByReference($variable)
         $parent = $this->getNode($variable->getParent());
 
         if ($parent && $parent instanceof ASTArguments) {
-            $argumentPosition = array_search($this->getNode($variable), $parent->getChildren());
-            $function = $this->getNode($parent->getParent());
-            $functionName = $function->getImage();
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:280]: Can we keep the intermediate variable for readability and debuggability as ``$functionName = $this->getNode($parent->getParent())->getImage();``?

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 4]
```diff
@@ -264,6 +264,33 @@ protected function getNode($node)
...
     }
 
+    /**
+     * Reflect function trying as namespaced function first, then global function.
+     *
+     * @param string $functionName
+     *
+     * @return ReflectionFunction|null
+     */
+    private function getReflectionFunction($functionName)
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:274]: ``getReflectionFunctionFromFunctionName``?

File: src/main/php/PHPMD/Node/Annotation.php (hunk 1 above)
Comment (kylekatarnls) [reply src/main/php/PHPMD/Node/Annotation.php:21]: No idea 😮

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php (hunk 3 above)
Comment (kylekatarnls) [reply src/main/php/PHPMD/Rule/AbstractLocalVariable.php:280]: OK, note than when debugging you can "evaluate expression" to check intermediate values.

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php (hunk 4 above)
Comment (kylekatarnls) [reply src/main/php/PHPMD/Rule/AbstractLocalVariable.php:274]: Maybe FromName or ByName is enough without repeating "Function"?

Comment (ravage84) [reply src/main/php/PHPMD/Rule/AbstractLocalVariable.php]: Agreed

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php (hunk 3 above)
Comment (ravage84) [reply src/main/php/PHPMD/Rule/AbstractLocalVariable.php:280]: Thanks, I am aware.

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 5]
```diff
@@ -264,6 +264,32 @@ protected function getNode($node)
...
+            $chunks = explode('\\', $functionName);
+
+            if (count($chunks) > 1) {
+                try {
+                    return new ReflectionFunction(end($chunks));
+                } catch (ReflectionException $exception) {
+                    // @TODO: Find a way to handle user-land functions
+                    // @TODO: Find a way to handle methods
+                }
+            }
```
Comment (tvbeek) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:287]: Isn't it more logic to place the code below the catch because it does nothing with the exception?

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 6]
```diff
@@ -285,15 +311,14 @@ protected function isPassedByReference($variable)
                 return false;
             }
 
-            try {
-                $reflectionFunction = new ReflectionFunction($functionName);
+            $reflectionFunction = $this->getReflectionFunctionByName($functionName);
+
+            if ($reflectionFunction) {
```
Comment (tvbeek) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:316]: I found it more readable to return early, do you share that opinion?

```php
$reflectionFunction = $this->getReflectionFunctionByName($functionName);
if (!$reflectionFunction) {
    return false;
}
```

Maybe it can be applied to the whole function in this PR.

**Review by tvbeek — APPROVED** [review]
