### PR TITLE
Fix #714 Improve static member detection

### LINKED ISSUE #714: Undefined Variable Rule does not understand static class variables.
- PHPMD version: 2.8.0
- PHP Version: 7.2.25
- Installation type: composer
- Operating System / Distribution & Version: Debian 9.6

### Current Behavior
The new feature "Undefined Variable Rule" introduced in https://github.com/phpmd/phpmd/pull/497 
 is not working with **static** class variables, such as 
```php
class CmsBlock
{
    protected static $cmsBlockBuffer = [];

    protected function getCmsBlockById(string $cmsBlockKey): array
    {
        if (isset(static::$cmsBlockBuffer[$cmsBlockKey])) {
            return static::$cmsBlockBuffer[$cmsBlockKey];
        }
     
        return static::$cmsBlockBuffer[$cmsBlockKey] = $this->findCmsBlockByKey($cmsBlockKey);
    }
}
```
PhpMd triggers error message `Avoid using undefined variables such as '$cmsBlockBuffer' which will lead to PHP notices.`

### Expected Behavior
No error messages.

### Steps To Reproduce:
Explain **all** the steps you did to create this bug so we can reproduce it.

## Checks before submitting
* [+] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [+] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [+] I have added every step to reproduce the bug.
* [+] If possible I added relevant code examples.
* [+] This issue is about 1 bug and nothing more.
* [+] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix  
Issue: Resolves #714
Breaking change: no

### CODE REVIEW

File: src/test/php/PHPMD/AbstractTest.php [hunk 1]
```diff
@@ -253,7 +253,7 @@ protected function expectRuleHasViolationsForFile(Rule $rule, $expectedInvokes,
 
         if (!$assertion) {
             throw new PHPUnit_Framework_ExpectationFailedException(
-                $this->getViolationFailureMessage($file, $actualInvokes, $expectedInvokes, $violations)
+                $this->getViolationFailureMessage($file, $expectedInvokes, $actualInvokes, $violations)
```
Comment (tvbeek) [inline src/test/php/PHPMD/AbstractTest.php:256]: This isn't really part of this PR but because it is a very small PR I will not block it for this.

**Review by tvbeek — APPROVED** [review]

**Review by ravage84 — APPROVED** [review]

**Comment by koekaverna** [comment]
I have similar problem with `Symfony\Component\HttpFoundation\Response`
There is 
```php
    public static $statusTexts = [
        100 => 'Continue',
        101 => 'Switching Protocols',
        102 => 'Processing',            // RFC2518
```

So I have error when using `Response::$statusTexts[$statusCode]`.
