### PR TITLE
Fix multiple underscores in method name when allow-underscore-test is…

### LINKED ISSUE #851: allow-underscore-test for CamelCaseMethod gives unexpected results
- PHPMD version: 2.9.1
- PHP Version: 7.4
- Installation type: composer

# Current Behavior
Currently when the property `allow-underscore-test` is set to true for the `CamelCaseMethod` rule, method names like `test_that_something_is_ok` are not accepted while documentation says "Is it allowed to have underscores in test method names." 

Changing the regex in the rule to `/^test[a-zA-Z0-9]*([_][a-z][a-zA-Z0-9]*)*?$/` should fix the problem. 

# Expected behavior
Method like `test_that_something_is_ok` should be allowed as described in documentation

# Additional 
I could make a PR myself, but in the Unit tests the following is documented:

```
    /**
     * Tests that the rule does apply for a test method name
     * with multiple underscores even when one is allowed.
     *
     * @return void
     */
```

So I'm not sure what the expected behavior would be?

### PR DESCRIPTION
**Pull request by SanderSander**
Type: bugfix
Issue: Resolves #851 
Breaking change: no

This PR adds an extra test to allow methods like `test_some_action_i_do` currently only a single underscore is allowed. 
There was one test that tested methods with multiple underscores which is modified to test 2 consecutive underscores which shouldn't be allowed.

### CODE REVIEW

File: src/main/php/PHPMD/Rule/Controversial/CamelCaseMethodName.php [hunk 1]
```diff
@@ -74,7 +74,7 @@ public function apply(AbstractNode $node)
     protected function isValid($methodName)
     {
         if ($this->getBooleanProperty('allow-underscore-test') && strpos($methodName, 'test') === 0) {
-            return preg_match('/^test[a-zA-Z0-9]*([_][a-z][a-zA-Z0-9]*)?$/', $methodName);
+            return preg_match('/^test[a-zA-Z0-9]*([_][a-z][a-zA-Z0-9]*)*?$/', $methodName);
```
Comment (kylekatarnls) [inline src/main/php/PHPMD/Rule/Controversial/CamelCaseMethodName.php:77]:
```suggestion
            return preg_match('/^test[a-zA-Z0-9]*([_][a-z][a-zA-Z0-9]*)*$/', $methodName);
```

**Review by kylekatarnls — APPROVED** [review]

**Review by tvbeek — APPROVED** [review]
