### PR TITLE
Fix for short variables rule

### LINKED ISSUE #790: ShortVariable rule doesn't work inside foreach
- PHPMD version: PHPMD 2.8.1snapshot202002241446
- PHP Version: 7.3.18
- Installation type: phar file
- Operating System / Distribution & Version: Linux Mint 19.2 Cinnamon

### Current Behavior
It doesn't report short variables when it is inside a foreach.

### Expected Behavior
It should report short variables inside a foreach, like in the example below, it should report $n and $b variables as a short ones.

### Steps To Reproduce:
this snippet:
```php
<?php

namespace App\Test;

class Test
{
    public function testing()
    {
        $a = 1;
        echo $a;

        foreach ([1,2,3] as $n) {
            $b = $n;
            echo $b;
        }
    }
}
```

with this command:
`$ phpmd test.php text naming`

is resulting in: 
`/home/naldi/Desktop/test.php:9	Avoid variables with short names like $a. Configured minimum length is 3.`

and it's missing the lines 12 and 13 that has $n and $b short variables declared.

## Checks before submitting
* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by artem-prozorov**
Type: **bugfix**
Issue: Resolves #790 
Breaking change: no

The issue says that the PHPMD's ShortVariable rule skips variables inside foreach statements.

The reason for that is that the Rule checks the variable's context and skips it, if the variable has certain parents (https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Rule/Naming/ShortVariable.php#L172)
I guess, the idea was to skip short variables that were initialized inside loops, like `foreach ($values as $k => $v)`.
But the parents verification used recursion to check ALL parents.

I've refactored the method `isNameAllowedInContext` so that for foreach statement it skips only variables that are the immediate children of this statement.

The issue also expects that variables inside foreach loops are also processed and not skipped. I think the right way to do that is to add a new configuration for the ShortVariable rule, something like "Process variables inside loops" that would be false by default and run those checks only if this config is set to true. This would keep the backward compatibility. Anyway, I think this is more like a new feature and if accepted by you, would rather be made in its own PR.

### CODE REVIEW

File: src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php [hunk 1]
```diff
@@ -345,4 +345,24 @@ public function testRuleNotAppliesToVariablesFromExceptionsList()
...
+     * testRuleAppliesToVariablesWithinForeach
+     *
+     * @return void
+     */
+    public function testRuleAppliesToVariablesWithinForeach()
+    {
+        $rule = new ShortVariable();
+        $rule->addProperty('minimum', 3);
+        $rule->addProperty('exceptions', '');
+        $rule->setReport($this->getReportMock(2));
```
Comment (kylekatarnls) [inline src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php:359]: Shouldn't we get 5 viloations? $i, $a, $k, $v and $x?

File: src/main/php/PHPMD/Rule/Naming/ShortVariable.php [hunk 2]
```diff
@@ -171,12 +171,59 @@ private function getExceptionsList()
...
 
+    /**
+     * Checks if a short name is initialized within a foreach loop statement
+     *
+     * @param \PHPMD\AbstractNode $node
+     * @return boolean
+     */
+    protected function isInitializedInLoop(AbstractNode $node)
+    {
+        $exceptionVariables = [];
```
Comment (kylekatarnls) [inline src/main/php/PHPMD/Rule/Naming/ShortVariable.php:191]:
```suggestion
        $exceptionVariables = array();
```
For backward-compatibility (PHPMD is compatible PHP 5.3 => 8)

File: src/main/php/PHPMD/Rule/Naming/ShortVariable.php [hunk 3]
```diff
@@ -171,12 +171,59 @@ private function getExceptionsList()
...
+
+    /**
+     * Returns an array of parent nodes of the specified type
+     *
+     * @param \PHPMD\AbstractNode $node
+     * @return boolean
+     */
+    protected function getParentsOfType(AbstractNode $node, $type)
+    {
+        $parents = [];
```
Comment (kylekatarnls) [inline src/main/php/PHPMD/Rule/Naming/ShortVariable.php:213]:
```suggestion
        $parents = array();
```

File: src/main/php/PHPMD/Rule/Naming/ShortVariable.php [hunk 4]
```diff
@@ -171,12 +171,57 @@ private function getExceptionsList()
...
+        return in_array($node->getImage(), $exceptionVariables, true);
+    }
+
+    /**
+     * Returns an array of parent nodes of the specified type
+     *
+     * @param \PHPMD\AbstractNode $node
+     * @return boolean
+     */
+        $parents = array();
```
Comment (kylekatarnls) [inline src/main/php/PHPMD/Rule/Naming/ShortVariable.php:211]:
```suggestion
    protected function getParentsOfType(AbstractNode $node, $type)
    {
        $parents = array();
```

File: src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php (hunk 1 above)
Comment (artem-prozorov) [reply src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php:359]: $i, $k and $v and initialized right inside the foreach operator. The system is configured now to skip such variables and I left this as is. I expect the system to process only variables that are initializad inside foreach block but not inside the very foreach statement.
I wrote about it in PR comment.
Do you want to remove this at all so that all variables were process regardless of if they are initialized inside foreach statement?

File: src/main/php/PHPMD/Rule/Naming/ShortVariable.php [hunk 5]
```diff
@@ -171,12 +171,59 @@ private function getExceptionsList()
...
+        $exceptionVariables = array_filter(array_unique($exceptionVariables));
+
+        return in_array($node->getImage(), $exceptionVariables, true);
+    }
+
+    /**
+     * Returns an array of parent nodes of the specified type
+     *
+     * @param \PHPMD\AbstractNode $node
+     * @return boolean
```
Comment (kylekatarnls) [inline src/main/php/PHPMD/Rule/Naming/ShortVariable.php:209]: Fix wrong return type:
```suggestion
     * @return array
```

File: src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php (hunk 1 above)
Comment (kylekatarnls) [reply src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php:359]: Indeed, enforcing the length of the index/value could be a big change for many people.

But still I think in clean apps those variables should not be abbreviated neither.

Comment (artem-prozorov) [reply src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php:359]: Agreed.

I'd suggest making this one configurable. I will open a new issue for that and submit a PR in a while, okay?

Comment (kylekatarnls) [reply src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php:359]: Awesome! Thank you 🙏

**Comment by artem-prozorov** [comment]
@kylekatarnls I've added a configuration option to be able to configure if minimum length is allowed within foreach loops

**Comment by tvbeek** [comment]
@artem-prozorov Thanks for the PR!
