### PR TITLE
Fix false positive with static variable in function. fixes #870

### LINKED ISSUE #870: False-positive message "Avoid using undefined variables" on a static variable
- PHPMD version: 2.9.1
- PHP Version: 7.4.15
- Installation type: (dnf install php-phpmd-PHP-PMD)
- Operating System / Distribution & Version: (Fedora 33)

### Current Behavior
phpmd detect the usage of an undefined variable

### Expected Behavior
not throwing an error

### Steps To Reproduce:
Use this script:

```
<?php
function func() {
    static $test = 1;
    echo $test;
    $test++;
}
```
[andrew@localhost ~]$ phpmd ./test.php text cleancode
/home/andrew/test.php:4	Avoid using undefined variables such as '$test' which will lead to PHP notices.
/home/andrew/test.php:5	Avoid using undefined variables such as '$test' which will lead to PHP notices.

## Checks before submitting
* [ v ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [ ~ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)  (seems like this:  #714, #734, #803, #229, but this error occurs in the function, not in the class)
* [ v ] I have added every step to reproduce the bug.
* [ v ] If possible I added relevant code examples.
* [ v ] This issue is about 1 bug and nothing more.
* [ v ] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by Sylry**
Type: bugfix
Issue: Resolves #870
Breaking change: no

Thanks to @char101 who suggested the fix in the issue

### CODE REVIEW

File: src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToStaticVariableInFonction.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * For full copyright and license information, please see the LICENSE file.
+ * Redistributions of files must retain the above copyright notice.
+ *
+ * @author Manuel Pichler <mapi@phpmd.org>
+ * @copyright Manuel Pichler. All rights reserved.
+ * @license https://opensource.org/licenses/bsd-license.php BSD License
+ * @link http://phpmd.org/
+ */
+
+function testRuleDoesNotApplyToStaticVariableInFonction()
```
Comment (kylekatarnls) [inline src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToStaticVariableInFonction.php:18]: Fonction => Function (for file name + function name) 🙏

**Review by kylekatarnls — APPROVED** [review]
