### PR TITLE
Fix #672 Handle passing-by-reference in native PHP functions

### LINKED ISSUE #672: CleanCode\UndefinedVariable thrown unnecessarily with preg_match_all()
- PHPMD version: dev-master (SHA b9eaa0fe7f38c1f017a5ed8564f1cd63d136ed2c)
- PHP Version: 7.1.31
- Installation type: composer
- Operating System / Distribution & Version: MacOS X

### Current Behavior
UndefinedVariable error thrown unnecessarily when variable is guaranteed to be defined by `preg_match_all()`

### Expected Behavior
UndefinedVariable error not thrown for third argument to `preg_match_all()` when used.

### Steps To Reproduce:
The following code triggers the following warnings:
```
test.php:5	Avoid using undefined variables such as '$matches' which will lead to PHP notices.
test.php:6	Avoid using undefined variables such as '$matches' which will lead to PHP notices.
```
However, PHP won't throw warnings in this case, so the error is spurious. 

```php
<?php

function test()
{
    preg_match_all('/./', 'Text', $matches);
    foreach ($matches[0] as $match) {
        echo $match . PHP_EOL;
    }
}
```

There's also an inconsistency as the same code when not wrapped in a function does not throw the warnings (as I'd expect), e.g. the following code (correctly IMHO) does not generate an UndefinedVariable warning from PHPMD:

```php
<?php

preg_match_all('/./', 'Text', $matches);
foreach ($matches[0] as $match) {
    echo $match . PHP_EOL;
}
```

```
## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #672 ([confirmed](https://github.com/phpmd/phpmd/issues/672#issuecomment-630027978))
Breaking change: no

### CODE REVIEW

**Comment by kylekatarnls** [comment]
This feature use reflection to know if the current argument at the current position is passed by reference.

So this handles:
- native PHP functions like `preg_match_all` so it fixes the exact case of #672

But it doesn't handle:
- user-land functions
- class methods

Those other cases would require way more work to be handled, as definition of user-land functions can be in any other files (potentially not yet parsed) and they are not know by reflection (as it uses runtime and not static analysis).

For method, we currently have now generic way to know when calling `$foo->method()` what class `$foo` is an instance of and so to which definition `method` refers no matter it's a PHP-land or user-land class.

**Comment by kylekatarnls** [comment]
Side-note: this also uses methods (`getVariableImage` and `getNode`) introduced in #781 so it should remain draft until #781 is merged or declined. But the specific logic can yet be reviewed.

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 1]
```diff
@@ -84,9 +87,21 @@ protected function isLocal(ASTNode $variable)
...
+     * Tests if the given variable does not represent one of the PHP super globals
+     * that are available in scopes.
+     *
+     * @param \PHPMD\AbstractNode $variable
+     * @return boolean
+     */
     protected function isNotSuperGlobal(AbstractNode $variable)
     {
-        return !isset(self::$superGlobals[$variable->getImage()]);
+        return !$this->isSuperGlobal($variable);
```
Comment (tvbeek) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:104]: Nice cleanup for readability 👍

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php [hunk 2]
```diff
@@ -230,4 +245,35 @@ protected function getNode($node)
...
+
+            try {
+                $reflectionFunction = new ReflectionFunction($functionName);
+                $parameters = $reflectionFunction->getParameters();
+
+                if ($parameters[$argumentPosition]->isPassedByReference()) {
+                    return true;
+                }
+            } catch (ReflectionException $exception) {
+                // @TODO: Find a way to handle user-land functions
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/AbstractLocalVariable.php:272]: The ``@`` isn't necessary here.

File: src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php [hunk 3]
```diff
@@ -73,11 +73,11 @@ public function apply(AbstractNode $node)
         }
 
         foreach ($node->findChildrenOfType('Variable') as $variable) {
-            if (!$this->isNotSuperGlobal($variable)) {
-                $this->addVariableDefinition($variable);
-            }
+            /** @var ASTVariable $variable */
```
Comment (ravage84) [inline src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php:76]: Just a side thought. If we introduce a ``findChildrenOfVariable()`` method with a clear type hint, instead of ``findChildrenOfType('Variable')``, we do not need such inline type hints... What do you think?

Comment (kylekatarnls) [reply src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php:76]: Yes, Variable is common enough to have its own find method.

Comment (ravage84) [reply src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php:76]: https://github.com/phpmd/phpmd/pull/786

File: src/main/php/PHPMD/Rule/AbstractLocalVariable.php (hunk 2 above)
Comment (kylekatarnls) [reply src/main/php/PHPMD/Rule/AbstractLocalVariable.php:272]: Indeed, as it's in AbstractLocalVariable, I will fix it in #783 after conflicts resolved.
